---
title: "Gov 50 Final Project"
author: "Anastasia Leladze"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

How did new migration patterns caused by the Russo-Ukrainian war affect inflation in Georgia? In this project, I will be exploring how the increased number of Russian immigrants affected Georgian economy, and especially the inflation rate. From what I have observed in the country, the prices rose greatly while the government proudly publicized the 10% growth rate. I believe that Russians, trying to escape the economic sanctions, brought a lot of cash to Georgia and bought the local currency, Lari. This made Lari stronger compared to the dollar which seemed a positive dynamic. The increased amount of cash in the country did result in some kind of growth, with capital increasing and a new labor force coming into the country, but this stopped at some point. After that, the economy could not catch up with real growth, and more cash circulating resulted in increased prices. 

To check whether this is correct or not, I will need to look at exactly what the immigration patterns (independent variable) and how inflation rates over time responded to them (dependent variable). For both, I will rely on not only Georgian but also international statistical sources - mostly, "Geostats" and the World Bank. The outcome of our interest will be the change in the inflation rates caused by the migration. If my hypothesis is correct, the data will show that the inflation rate significantly increased with the amount of migrational inflow; if I am wrong, the numbers will show inflation's independence from migration or it is decreasing over time. While this seems a simple comparison, it will be very hard to account for the confounders in the economy, which usually exist in large numbers while dealing with unpredictable developing economies.

https://www.geostat.ge/ka/modules/categories/26/samomkhmareblo-fasebis-indeksi-inflatsia
https://www.geostat.ge/ka/modules/categories/316/mosakhleoba-da-demografia
https://data.worldbank.org/indicator/FP.CPI.TOTL.ZG?locations=GE
